### ISSUE TITLE
商品名：活けあわびの鉄板焼きと特選牛のお弁当 

### ISSUE THREAD

**Issue by ramkumarlama** [fatlightslim/otodoketai#111]
※個数が２個以上からの受付になる商品なので、１個では注文できないように設定できますか？

**Comment by k016k016** [comment]
対応しました。
管理画面では、１個に修正が可能な状態にしています。
ご確認をお願いいたします。
https://github.com/fatlightslim/otodoketai/pull/new/issue%23111

**Comment by ramkumarlama** [comment]
ありがとうございます。確認します。

**Comment by ramkumarlama** [comment]
#116
