### ISSUE TITLE
発注書に店舗店サインの場所が作ることができますか?

### ISSUE THREAD

**Issue by ramkumarlama** [fatlightslim/otodoketai#120]
![Uploading IMG_20210716_103609.jpg…]()

**Comment by k016k016** [comment]
@ramkumarlama  画像？が表示されていません。

**Comment by ramkumarlama** [comment]
![Uploading IMG_20210719_102958.jpg…]()

**Comment by ramkumarlama** [comment]
![image](https://user-images.githubusercontent.com/78124158/126090287-076880a2-d409-4cce-85d8-371e125a6931.png)

**Comment by k016k016** [comment]
クマル君対応お願いします。詳細は、Discordで送っています。

**Comment by ramkumarlama** [comment]
#138
