### ISSUE TITLE
領収書と発注書に備考欄の内容とお支払い決済を印字して欲しいです!

### ISSUE THREAD

**Issue by ramkumarlama** [fatlightslim/otodoketai#121]
![Uploading 16264017272096196388034360986006.jpg…]()

**Comment by k016k016** [comment]
@ramkumarlama  画像？が表示されていません。

**Comment by ramkumarlama** [comment]
![image](https://user-images.githubusercontent.com/78124158/126089897-9801cfdb-3a7f-4de7-b33f-08d20ba3afa5.png)

**Comment by k016k016** [comment]
クマル君が担当

**Comment by ramkumarlama** [comment]
#125

**Comment by ramkumarlama** [comment]
#135

**Comment by ramkumarlama** [comment]
#146

**Comment by ramkumarlama** [comment]
#148
