### ISSUE TITLE
アレルギーがないかどうかcheckできるようにしてほしい!

### ISSUE THREAD

**Issue by ramkumarlama** [fatlightslim/otodoketai#122]

**Comment by k016k016** [comment]
これはメニュー毎に
「アレルギーあり」
のチェックをcontentfullにつけて、チェックがあれば「アレルギーあり」とメニューに表示すればばいいですか？

**Comment by k016k016** [comment]
注文時、お客様がアレルギーあるかどうかの確認のためcheckboxにチェックを入れる
ように変更します。

**Comment by ramkumarlama** [comment]
#143
