### ISSUE TITLE
午前便と午後便を画面見たい出てほしい

### ISSUE THREAD

**Issue by ramkumarlama** [fatlightslim/otodoketai#128]
![image](https://user-images.githubusercontent.com/78124158/126091543-56bb0e3c-cfe3-4038-bd64-305768bca09a.png)

午前便と午後便がある時に画像みたいににならないって事でした。

**Comment by k016k016** [comment]
画像みたいになっていると思いますけど、画像みたいにならないのを詳しく教えてください。

**Comment by ramkumarlama** [comment]
ほんとだ！なってますね。もう一度確認してみます。

**Comment by ramkumarlama** [comment]
![image](https://user-images.githubusercontent.com/78124158/127833907-e7fc7ba3-aad7-4542-972a-8dca4045519c.png)
確認してみました。午後便と午前便同じ所並んでいます。こいう時午前便と午後便別々で出てほしいことでした。

**Comment by ramkumarlama** [comment]
#145
