### ISSUE TITLE
ネットでお弁当のご飯、普通、大盛、特盛の対応出来ますか？

### ISSUE THREAD

**Issue by ramkumarlama** [fatlightslim/otodoketai#131]
![Screenshot_20210720-063529_Word](https://user-images.githubusercontent.com/78124158/126248270-40b87f94-90d2-4908-9adb-99c7e0c96ed5.jpg)

**Comment by k016k016** [comment]
ご飯の普通、大盛、特盛をそれぞれ作成すればいいと思います。
@ramkumarlama

**Comment by ramkumarlama** [comment]
かしこまりました。
