### ISSUE TITLE
お買い物サポートと 食品事業部の発注書の名前の変更をお願いします。

### ISSUE THREAD

**Issue by ramkumarlama** [fatlightslim/otodoketai#136]
お買い物サポート→みのりの郷東金

また、お買い物サポートの商品には番号も付けてほしいとのことだったので、商品名のところに番号も入れてください。

YC東金中央　食品事業部　→　矢仲

**Comment by k016k016** [comment]
yamamoto作業中

**Comment by ramkumarlama** [comment]
#141
