### ISSUE TITLE
阿比留さんへ　content(商品追加）

### ISSUE THREAD

**Issue by ramkumarlama** [fatlightslim/otodoketai#27]
contentで新商品を追加と今月やらない店をunpblishedしてありますが（otodoketai.vercel.app）ホームページに出てこないですのでもしかして僕が追加し方間違えてるか確認してもらっていいんですか？

**Comment by fatlightslim** [comment]
pages/index.js getStaticPropsからgetServerSidePropsに変更
https://nextjs.org/docs/basic-features/data-fetching
