### ISSUE TITLE
定休日は注文できないように

### ISSUE THREAD

**Issue by ramkumarlama** [fatlightslim/otodoketai#47]

**Comment by ramkumarlama** [comment]
@abiru さんcontentfulの全部メニューに月曜日にチェックすれば定休日に注文できないようになるかな？
一応定月曜日にチェックしてありますけど...

**Comment by abiru** [comment]
うまく動いてないからオレが修正するよ。

**Comment by ramkumarlama** [comment]
助かります。よろしくお願いいたします。
