### ISSUE TITLE
発注書の合計金額は店舗ごとに合計は同じになってます。

### ISSUE THREAD

**Issue by ramkumarlama** [fatlightslim/otodoketai#55]

**Comment by k016k016** [comment]
全部の店舗の合計金額が、各店舗の合計金額に表示されているので、各店舗毎の合計金額を表示するようにお願いします。

**Comment by ajimura1** [comment]
掲載店の萬福飯店さん以外のお店は掲載料金から10%を読売がもらっています。
萬福飯店さんだけ550円の掲載料金で、500円が萬福さんへ50円が読売に入るようになっています。
発注書の金額が500円となります。
よろしくお願いします。味村

**Comment by k016k016** [comment]
萬福飯店の時、
単価から50円引いた金額が値段になり、
その合計金額を発注書の合計金額にする。

それ以外の店舗の時、
単価から10%引いた金額が値段になり、
その合計金額を発注書の合計金額にする。

という考え方でよろしいでしょうか？

**Comment by ajimura1** [comment]
そうです。よろしくお願いします。

**Comment by k016k016** [comment]
@ajimura1 
回答ありがとうございます。

@ramkumarlama 
今日の昼に説明したやり方にちょっと工夫がいるかもしれないので、ちょっと考えます。

**Comment by ajimura1** [comment]
よろしくお願い致します。
