### ISSUE TITLE
発注書はPDFで出力する

### ISSUE THREAD

**Issue by fatlightslim** [fatlightslim/otodoketai#87]

**Comment by fatlightslim** [comment]
http://faq3.dospara.co.jp/faq/show/4698?category_id=22&site_domain=default#:~:text=%5B%20%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%20%5D%20%E3%82%92%E3%82%AF%E3%83%AA%E3%83%83%E3%82%AF%E3%81%97%E3%80%81,)%20%5D%20%E3%82%92%E3%82%AF%E3%83%AA%E3%83%83%E3%82%AF%E3%81%97%E3%81%BE%E3%81%99%E3%80%82&text=%E3%80%8C%20%E5%8D%B0%E5%88%B7%E3%81%AE%E5%90%91%E3%81%8D%20%E3%80%8D%20%E3%82%92%E9%81%B8%E6%8A%9E%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%80%82

**Comment by abiru** [comment]
@ramkumarlama 金子さんからの要望ですが、PDFで発注書を出力したいようです。↑のやり方で大丈夫だと思うので、皆さんに教えてあげてください。

**Comment by ramkumarlama** [comment]
@abiru かしこまりました。
