### ISSUE TITLE
味良さんだけ、当日配達出来ないので設定お願いします。

### ISSUE THREAD

**Issue by ramkumarlama** [fatlightslim/otodoketai#99]

**Comment by k016k016** [comment]
これできてるような気がするけど、どういうとき、当日配達できないんですか？

**Comment by ramkumarlama** [comment]
今は当日だと17：00～18：00時の注文できるようになってますが味良店だけ当日注文じゃなくて明日の日にちと時間で注文できるようにしてことでした！すみません、うまく説明できなくて

**Comment by k016k016** [comment]
味良さんは、
当日注文はできない。
次の日の17：00～18：00は予約可能。
次の日以降は、11：00～12：00　と　17：00～18：00。
が予約可能に今、なってますね。

**Comment by k016k016** [comment]
配送可能な日時について、正しい動きがわからないので教えてください。
また、味良さんについても配送可能な日時を教えてください。

**Comment by ramkumarlama** [comment]
味良さんは当日受付け出来ませんが
翌日11時～12時と夕方17時～18時の受付が出来ます。って事でした！
![image](https://user-images.githubusercontent.com/78124158/125409525-f1048f80-e3f6-11eb-8bcb-157746df4333.png)
今だと当日配達出来てます。

**Comment by k016k016** [comment]
pull request 送ってます。ご確認とマージお願いします。

**Comment by ramkumarlama** [comment]
かしこまりました。

**Comment by ramkumarlama** [comment]
#124
